version: '2'
services:
  userdb:
    container_name: userdb
    image: postgres:12.11
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hithttp
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
        - 8080:8080